### ISSUE TITLE
possible addition

### ISSUE THREAD

**Issue by palmbeach05** [Resurrection3387/device_samsung_msm8916-common#2]
https://github.com/Resurrection3387/device_samsung_msm8916-common/blob/56550765dd2059b3a863df112fde6929a90525bd/overlay/frameworks/base/core/res/res/values/config.xml#L196

    
    <bool name="config_device_volte_available">true</bool>

    
    <bool name="config_carrier_volte_available">true</bool>

**Comment by palmbeach05** [comment]
Also, while it may be in the direction of another manufacturer, this may shed some light on why volte was not available to us on any non tw based rom

https://github.com/MotorolaMobilityLLC/kernel-msm/issues/85

Its a lot to take in, but logically thinking, our maintainers, pre-geg era, did not fully develop things (i.e., NFC, also broken until now). Its worth sitting down and looking at it, if not you, then SebaUbuntu might be able to jump on board and assist. I'll keep trying to make heads or tails of things

**Comment by zakaryan2004** [comment]
> Also, while it may be in the direction of another manufacturer, this may shed some light on why volte was not available to us on any non tw based rom
> 
> https://github.com/MotorolaMobilityLLC/kernel-msm/issues/85
> 
> Its a lot to take in, but logically thinking, our maintainers, pre-geg era, did not fully develop things (i.e., NFC, also broken until now). Its worth sitting down and looking at it, if not you, then SebaUbuntu might be able to jump on board and assist. I'll keep trying to make heads or tails of things

No. VoLTE is *not* like NFC. While there were lots of other msm8916 devices which had NFC working, there is no *Samsung device on AOSP* which has VoLTE working. VoLTE is deeply buried on Samsung's framework.jar and heavily depends on other Samsung shit, meaning it's technically impossible to take VoLTE out from there and get it working. That Motorola device(and every other one) on the other hand, has their VoLTE implementation more accessible, in ims.apk, and this allows the use of VoLTE in AOSP with necessary configuration, unlike in any Samsung device. Well, maybe you can do something no one has done before..? Who knows. Good luck.

**Comment by SebaUbuntu** [comment]
+1 at @zakaryan2004 
It's literally impossible

**Comment by Resurrection3387** [comment]
Should I close this issue?

**Comment by SebaUbuntu** [comment]
> Should I close this issue?

Yes

**Comment by Resurrection3387** [comment]
> +1 at @zakaryan2004
> It's literally impossible

It is possible just very difficult

**Comment by SebaUbuntu** [comment]
And BTW how tf GitHub have real-time chatting capabilities lol

**Comment by Resurrection3387** [comment]
That's cool I guess. Anyways, closing the issue.

**Comment by zakaryan2004** [comment]
> And BTW how tf GitHub have real-time chatting capabilities lol

Well, _teamwork_
